/*
    Project Euler Problem No. 45 - Triangular, pentagonal, and hexagonal

Trangle, pentagonal, and hexagonal numbers are generated by the following 
formulae:

Triangle        Tn=n*(n+1)/2     1, 3, 6, 10, 15, ...
Pentagonal      Pn=n*(3*n-1)/2   1, 5, 12, 22, 35, ...
Hexagonal       Hn=n*(2*n-1)     1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
 */

package main

import "fmt"

const Max int64 = 6e4

/*
func triangleNums(max int) []int {

    nums := make([]int, max + 1)
    nums[0] = 0

    for cnt := 1; cnt <= max; cnt++ {
        nums[cnt] = cnt * (cnt + 1) / 2
    }
    return nums
}

func pentagonalNums(max int) []int {

    nums := make([]int, max + 1)
    nums[0] = 0

    for cnt := 1; cnt <= max; cnt++ {
        nums[cnt] = cnt * (3 * cnt - 1) / 2
    }
    return nums
}

func hexagonalNums(max int) []int {

    nums := make([]int, max + 1)
    nums[0] = 0

    for cnt := 1; cnt <= max; cnt++ {
        nums[cnt] = cnt * (2 * cnt - 1)
    }
    return nums
}
*/

func main() {
c := `Project Euler Problem No. 45 - Triangular, pentagonal, and hexagonal

Trangle, pentagonal, and hexagonal numbers are generated by the following 
formulae:

Triangle        Tn=n*(n+1)/2     1, 3, 6, 10, 15, ...
Pentagonal      Pn=n*(3*n-1)/2   1, 5, 12, 22, 35, ...
Hexagonal       Hn=n*(2*n-1)     1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.`
    fmt.Println(c)
    fmt.Println()

    var num int64 = 0
    var t, p, h int64 = 0, 0, 0
    var i, j, k int64 = 0, 0, 0
    for i = 285; i < Max; i++ {
        t = i * (i + 1) / 2
        for j = 165; p <= t || j < Max; j++ {
            p = j *(3 * j - 1) / 2
            if t == p {
                for k = 144; h <= t || k < Max; k++ {
                    h = k * (2 * k - 1)
                    if h == t {
                        num = t
                        //fmt.Printf("DEBUG: i=%d, j=%d, k=%d\n", i,j,k)
                        goto end
                    }
                }
            }
        }
    }

end:
    fmt.Printf("The next triangle number is %d.\n", num)
}
